-- MySQL Script generated by MySQL Workbench
-- Sun Dec 10 14:29:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`institucion` (
  `id_institucion` INT(7) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_institucion`));


-- -----------------------------------------------------
-- Table `mydb`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facultad` (
  `id_facultad` INT(7) NOT NULL,
  `id_institucion` INT(7) NOT NULL,
  `nombre` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_facultad`, `id_institucion`),
  INDEX `created_by_idx` (`id_institucion` ASC) VISIBLE,
  CONSTRAINT `created_by`
    FOREIGN KEY (`id_institucion`)
    REFERENCES `mydb`.`institucion` (`id_institucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumno` (
  `no_cuenta` INT(7) NOT NULL,
  `id_facultad` INT(7) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido_materno` VARCHAR(30) NOT NULL,
  `apellido_paterno` VARCHAR(30) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `clave` VARCHAR(45) NOT NULL,
  `perdiodo_ingreso` VARCHAR(3) NOT NULL,
  `periodo_egreso` VARCHAR(3) NULL,
  `sexo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`no_cuenta`, `id_facultad`),
  UNIQUE INDEX `no_cuenta_UNIQUE` (`no_cuenta` ASC) VISIBLE,
  INDEX `created_by_idx` (`id_facultad` ASC) VISIBLE,
  CONSTRAINT `created_by`
    FOREIGN KEY (`id_facultad`)
    REFERENCES `mydb`.`facultad` (`id_facultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `no_cuenta` INT(7) NOT NULL,
  `facultad` INT(7) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `apellido_materno` VARCHAR(32) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(32) NOT NULL,
  `puesto` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`no_cuenta`, `facultad`),
  INDEX `created_by_idx` (`facultad` ASC) VISIBLE,
  CONSTRAINT `created_by`
    FOREIGN KEY (`facultad`)
    REFERENCES `mydb`.`facultad` (`id_facultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`externo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`externo` (
  `id_externo` INT NULL,
  `id_institucion` INT(7) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `nivel_educativo` VARCHAR(20) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_externo`, `id_institucion`),
  INDEX `created_by_idx` (`id_institucion` ASC) VISIBLE,
  CONSTRAINT `created_by`
    FOREIGN KEY (`id_institucion`)
    REFERENCES `mydb`.`institucion` (`id_institucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`edificioB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`edificioB` (
  `id_edificiob` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `acervo_bibliografico` INT NOT NULL,
  `area_abierta_vitral` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `auto_acceso` INT NOT NULL,
  `area_estudio` INT NOT NULL,
  PRIMARY KEY (`id_edificiob`, `id_usuario`),
  INDEX `create_by_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `create_by`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`alumno` (`no_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `create_by`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`externo` (`id_externo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `create_by`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`empleado` (`no_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
